import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-rxjs-demo',
  templateUrl: './rxjs-demo.component.html',
  styleUrls: ['./rxjs-demo.component.css']
})
export class RxjsDemoComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  getData_click()
  {

    let observableObj = new Observable( (subscriber) => {
      subscriber.next("Data generated by observable -- 1");
      subscriber.next("Data generated by observable -- 2");
      subscriber.next("Data generated by observable -- 3");
    });


    observableObj.subscribe( (data:any) =>
    {
      console.log(data);
    } );


  }

}
