import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-rxjs-demo',
  templateUrl: './rxjs-demo.component.html',
  styleUrls: ['./rxjs-demo.component.css']
})
export class RxjsDemoComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  getData_click()
  {

    let observableObj = new Observable( (subscriber) => {

     let x = 22;

     if(x % 2 == 0)
         subscriber.next("Data generated by observable -- " + x);
     else
         subscriber.error("Error Occurred while processing observable");
   });




   observableObj.subscribe(
     {
        next  :  (resData:any) =>  { console.log(resData); },
        error  : (errorData:any) =>  { console.log("Error Handled by code : " + errorData); },
     }
    );


  }

}
