import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-rxjs-demo',
  templateUrl: './rxjs-demo.component.html',
  styleUrls: ['./rxjs-demo.component.css']
})
export class RxjsDemoComponent implements OnInit {

  strResult: string = "";

  constructor() { }

  ngOnInit(): void {
  }

  getData_click()
  {

    let observableObj = new Observable( (subscriber) => {

      let x = 22;

     if(x % 2 == 0)
         subscriber.next("Data generated by observable -- " + x);
     else
         subscriber.error("Error Occurred while processing observable");
   });

   // subscribe or consuming observables
   observableObj.subscribe(
     {
      next :  (result:any) =>  {
         this.strResult = "Response from Observable: " + result;
         console.log(result);
       },
       error : (error:any) =>  {
         this.strResult = "Error from Observable: " + error;
           console.log(error);   }
       });
  }
}
